//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseSite.Models.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CenterDBEntities : DbContext
    {
        public CenterDBEntities()
            : base("name=CenterDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Corporates> Corporates { get; set; }
        public virtual DbSet<CorporatesStatus> CorporatesStatus { get; set; }
        public virtual DbSet<Course_Instractors> Course_Instractors { get; set; }
        public virtual DbSet<Course_status> Course_status { get; set; }
        public virtual DbSet<Courses> Courses { get; set; }
        public virtual DbSet<Customerabsent> Customerabsent { get; set; }
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<CustomerStatus> CustomerStatus { get; set; }
        public virtual DbSet<FAQs> FAQs { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<GroupCustomers> GroupCustomers { get; set; }
        public virtual DbSet<GroupStatus> GroupStatus { get; set; }
        public virtual DbSet<Instractors> Instractors { get; set; }
        public virtual DbSet<InstractorStatus> InstractorStatus { get; set; }
        public virtual DbSet<schedules> schedules { get; set; }
        public virtual DbSet<Specifications> Specifications { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<CompanyProfile> CompanyProfile { get; set; }
        public virtual DbSet<Groups> Groups { get; set; }
    }
}
