//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseSite.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyProfile
    {
        public string CompanyNameEng { get; set; }
        public string CompanyNameAra { get; set; }
        public string CompanyAddress_FlatNumber { get; set; }
        public string CompanyAddress_StreetNameEng { get; set; }
        public string CompanyAddress_StreetNameAra { get; set; }
        public string CompanyAddress_DistricNameEng { get; set; }
        public string CompanyAddress_DistricNameAr { get; set; }
        public string CompanyAddress_CityNameEng { get; set; }
        public string CompanyAddress_CityNameAra { get; set; }
        public string CompanyAddress_CountryNameEng { get; set; }
        public string CompanyAddress_CountryNameAra { get; set; }
        public string CompanyPhone1 { get; set; }
        public string CompanyPhone2 { get; set; }
        public string CompanyEmail { get; set; }
        public string CompanySummarEng { get; set; }
        public string CompanySummaryAra { get; set; }
        public string CompanyVideoPath { get; set; }
        public string CompanyImagePath { get; set; }
        public string CompanyObjectiveEng { get; set; }
        public string CompanyObjectiveAra { get; set; }
        public string CompanyHeadLineEng { get; set; }
        [Display(Name = "Arabic HeadLine")]
        public string CompanyHeadLineAra { get; set; }
        public int ID { get; set; }

        public string CompanyHeadLineAra { get; set; }
        //bda8897219d551403cc11b19ea69b08aded921bd
    }
}
