//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseSite.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Corporates
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Corporates()
        {
            this.Customers = new HashSet<Customers>();
        }
    
        public int ID { get; set; }
        public string Corporates_EngName { get; set; }
        public string Corporates_AraName { get; set; }
        public string Corporates_Address { get; set; }
        public string Corporates_phone { get; set; }
        public string Corporates_mobile { get; set; }
        public string Corporates_email { get; set; }
        public string Corporates_FocalPoint { get; set; }
        public string Corporates_Summary { get; set; }
        public string Corporates_ImagePath1 { get; set; }
        public string Corporates_imagePath2 { get; set; }
        public Nullable<int> Corporates_statusId { get; set; }
    
        public virtual CorporatesStatus CorporatesStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customers> Customers { get; set; }
        public virtual CorporatesStatus CorporatesStatus1 { get; set; }
    }
}
