    //------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseSite.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course_Instractors
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course_Instractors()
        {
            this.Groups = new HashSet<Groups>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CourseID { get; set; }
        public Nullable<int> InstractorID { get; set; }
        public Nullable<int> SpecificationID { get; set; }
    
        public virtual Courses Courses { get; set; }
        public virtual Specifications Specifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Groups> Groups { get; set; }
        public virtual Instractors Instractors { get; set; }
    }
}
