//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseSite.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Courses
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Courses()
        {
            this.Course_Instractors = new HashSet<Course_Instractors>();
        }
    
        public int ID { get; set; }
        public string Course_EngName { get; set; }
        public string Course_AraName { get; set; }
        public string Course_VedioPath { get; set; }
        public string Course_ImgePath { get; set; }
        public string Course_ImagePath2 { get; set; }
        public string Course_EngObjective { get; set; }
        public string Course_AraObjective { get; set; }
        public string Course_EngSummary { get; set; }
        public string Course_AraSummary { get; set; }
        public string Course_ArabicContentPath { get; set; }
        public string Course_EnglishContent { get; set; }
        public Nullable<int> Course_StatusID { get; set; }
        public Nullable<decimal> Course_TotalHour { get; set; }
        public Nullable<decimal> Course_OrignalCost { get; set; }
        public Nullable<System.DateTime> Course_CreationDate { get; set; }
        public string Course_CreationUsers { get; set; }
        public Nullable<System.DateTime> Course_ModifyDate { get; set; }
        public string Course_modifyUsers { get; set; }
        public Nullable<bool> Course_ISInMain { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course_Instractors> Course_Instractors { get; set; }
        public virtual Course_status Course_status { get; set; }
    }
}
