//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseSite.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customers()
        {
            this.GroupCustomers = new HashSet<GroupCustomers>();
        }
    
        public int ID { get; set; }
        public string Customer_EngName { get; set; }
        public string Customer_AraName { get; set; }
        public string Customer_Phone { get; set; }
        public string Customer_Mobile { get; set; }
        public Nullable<System.DateTime> Customer_Birthdate { get; set; }
        public string Customer_Address { get; set; }
        public string Customer_Email { get; set; }
        public string Customer_Comment { get; set; }
        public Nullable<int> Customer_GenderId { get; set; }
        public string Customer_imagePath { get; set; }
        public string Customer_Nid { get; set; }
        public Nullable<int> Customer_CorporateID { get; set; }
        public Nullable<int> Customer_statusID { get; set; }
    
        public virtual Corporates Corporates { get; set; }
        public virtual CustomerStatus CustomerStatus { get; set; }
        public virtual Gender Gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupCustomers> GroupCustomers { get; set; }
    }
}
