//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseSite.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAQs
    {
        public int FAQ_ID { get; set; }
        public string FAQ_QuestionEng { get; set; }
        public string FAQ_QuestionAra { get; set; }
        public string FAQ_AnswerEng { get; set; }
        public string FAQ_AnswerAra { get; set; }
        public bool FAQ_Status { get; set; }
        public string FAQ_CreattonUser { get; set; }
        public Nullable<System.DateTime> FAQ_CreationDate { get; set; }
        public string FAQ_ModifiedUser { get; set; }
        public Nullable<System.DateTime> FAQ_ModifiedDate { get; set; }
    
        public virtual FAQs FAQs1 { get; set; }
        public virtual FAQs FAQs2 { get; set; }
    }
}
