//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseSite.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Groups
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Groups()
        {
            this.GroupCustomers = new HashSet<GroupCustomers>();
            this.schedules = new HashSet<schedules>();
        }
    
        public int Group_ID { get; set; }
        public Nullable<System.DateTime> Group_CreationDate { get; set; }
        public string Group_CreationUser { get; set; }
        public Nullable<System.DateTime> Group_modifiedDate { get; set; }
        public string Group_modifiedUser { get; set; }
        public Nullable<int> Group_CourseInstractorID { get; set; }
        public Nullable<System.DateTime> Group_StartDate { get; set; }
        public Nullable<System.DateTime> Group_EndDate { get; set; }
        public Nullable<decimal> Group_CostPerPerson { get; set; }
        public Nullable<int> Group_SessionNumber { get; set; }
        public Nullable<byte> Group_hoursPerSession { get; set; }
        public Nullable<int> Group_statusID { get; set; }
        public Nullable<byte> Group_CustomerNumber { get; set; }
        public string Group_ImagePath { get; set; }
        public string Group_ImagePath2 { get; set; }
    
        public virtual Course_Instractors Course_Instractors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupCustomers> GroupCustomers { get; set; }
        public virtual GroupStatus GroupStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<schedules> schedules { get; set; }
    }
}
