//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseSite.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupCustomers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GroupCustomers()
        {
            this.Customerabsent = new HashSet<Customerabsent>();
        }
    
        public int GroupCustomer_ID { get; set; }
        public Nullable<int> GroupCustomer_CustomerID { get; set; }
        public Nullable<int> GroupCustomer_GroupID { get; set; }
        public Nullable<decimal> GroupCustomer_payingCost { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customerabsent> Customerabsent { get; set; }
        public virtual Customers Customers { get; set; }
        public virtual Groups Groups { get; set; }
    }
}
