//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseSite.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instractors
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Instractors()
        {
            this.Course_Instractors = new HashSet<Course_Instractors>();
        }
    
        public int ID { get; set; }
        public string Instractor_EngName { get; set; }
        public string Instractor_AraName { get; set; }
        public string Instractor_Address { get; set; }
        public string Instractor_Mobile { get; set; }
        public string Instractor_phone { get; set; }
        public string Instractor_Email { get; set; }
        public Nullable<int> Instractor_StatusID { get; set; }
        public Nullable<int> Instractor_GenderID { get; set; }
        public Nullable<System.DateTime> Instractor_Birthdate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course_Instractors> Course_Instractors { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual InstractorStatus InstractorStatus { get; set; }
    }
}
