//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseSite.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class schedules
    {
        public int Schedule_ID { get; set; }
        public Nullable<int> Schedule_GroupID { get; set; }
        public System.DateTime Schedule_DatetimeFrom { get; set; }
        public Nullable<System.DateTime> Schedule_DateTimeTo { get; set; }
        public Nullable<System.DateTime> Schedule_CreationDate { get; set; }
        public string Schedule_CreationUser { get; set; }
        public Nullable<System.DateTime> Schedule_ModifiedDate { get; set; }
        public string Schedule_ModifiedUser { get; set; }
    
        public virtual Groups Groups { get; set; }
    }
}
