//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseSite.Models.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Specifications
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Specifications()
        {
            this.Course_Instractors = new HashSet<Course_Instractors>();
        }

        public int ID { get; set; }
        [DisplayName("Eng_Name")]
        public string Specification_EngName { get; set; }
        [DisplayName("Ar_Name")]
        public string Specification_AraName { get; set; }
        [DisplayName("Eng_Description")]
        [DataType(DataType.MultilineText)]
        public string Specification_EngDescription { get; set; }
        [DisplayName("Ar_Description")]
        [DataType(DataType.MultilineText)]
        public string Specification_AraDescription { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course_Instractors> Course_Instractors { get; set; }
    }
}
